name: Deploy Frontend to Arbutus Cloud Instance

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main # Runs this workflow on every push to the 'main' branch.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: m2b3/scicommons-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Set up Docker metadata (tags and labels)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Step 4: Build and push Docker image to GitHub Packages
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # Step 5: Setup SSH keys and known_hosts
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # Step 6: Deploy Docker image to the VPS via SSH
      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            echo "Pulling the latest image..."
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main

            # Get the currently running image ID
            CURRENT_IMAGE_ID=$(docker inspect --format="{{.Image}}" scicommons || echo "")
            
            # Check if the container exists
            if [ "$(docker ps -aq -f name=scicommons)" ]; then
              echo "Stopping and removing the existing container..."
              docker stop scicommons || true
              docker rm scicommons || true
            fi
            
            echo "Running the new container..."
            docker run -d --name scicommons \
              --env NEXT_PUBLIC_BACKEND_URL='${{ secrets.NEXT_PUBLIC_BACKEND_URL }}' \
              -p 80:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
            
            # Get the image ID of the new container
            NEW_IMAGE_ID=$(docker inspect --format="{{.Image}}" scicommons)
            
            echo "Cleaning up old images..."
            
            # Get a list of all images, excluding the new and currently running image (if available)
            IMAGES_TO_REMOVE=$(docker images -q | grep -v -e "$NEW_IMAGE_ID" -e "$CURRENT_IMAGE_ID" | sort | uniq)
            
            # If there are any images to remove, delete them
            if [ -n "$IMAGES_TO_REMOVE" ]; then
              echo "Removing the following images:"
              echo "$IMAGES_TO_REMOVE"
              docker rmi -f $IMAGES_TO_REMOVE || true
            else
              echo "No images to remove."
            fi
            
            echo "Deployment complete."
          EOF
