name: Test SSH Connection to VPS

# Allow manual triggering of the workflow
on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Step 1: Checkout the repository (optional, but often included)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup SSH keys and known_hosts, and log each step
      - name: Setup SSH and Log Output
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "Private key saved to ~/.ssh/id_rsa"
          chmod 600 ~/.ssh/id_rsa
          echo "Permissions set for private key"

          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          echo "Host key added to known_hosts for ${{ secrets.VPS_HOST }}"

          echo "Contents of known_hosts:"
          cat ~/.ssh/known_hosts

      # Step 3: Test SSH connection to VPS
      - name: Test SSH Connection
        id: action-ssh
        uses: tiyee/action-ssh@release
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 22
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: whoami
